version: "3.9"

services:
  # user guest/guest
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management
    ports:
      - "5679:5672"
      - "15679:15672"

  redis:
    restart: unless-stopped
    image: redis:alpine
    command: redis-server --requirepass testpass
    ports:
        - "6379:6379"
    volumes:
        - redis-data-volume:/data

  publisher:
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfilePublisher
    ports:
      - "5005:5000"
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672

  consumer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfileConsumer
    ports:
      - "5006:5000"
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672

volumes:
    redis-data-volume: